/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>
#include <string.h>

// Response structure for C
typedef struct {
    int status_code;
    char* body;
    int body_len;
    char* headers;
    char* url;
    char* error;
    char* protocol;
} CFfiResponse;

// Request structure for C
typedef struct {
    char* method;
    char* url;
    char* body;
    char* headers;
    char* proxy;
    int timeout_ms;
    int force_http1;
    int force_http3;
    int ignore_body;
    int no_cookie;
    int disable_redirects;
    int max_redirects;
    int insecure_skip_verify;
} CFfiRequest;

// Session configuration structure
typedef struct {
    char* browser;
    char* user_agent;
    char* proxy;
    int timeout_ms;
    int max_redirects;
    int insecure_skip_verify;
    char* headers;
} CFfiSessionConfig;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern GoUintptr azuretls_session_new(char* configJSON);
extern void azuretls_session_close(GoUintptr sessionID);
extern CFfiResponse* azuretls_session_do(GoUintptr sessionID, char* requestJSON);
extern CFfiResponse* azuretls_session_do_bytes(GoUintptr sessionID, char* method, char* url, char* headersJSON, unsigned char* body, size_t bodyLen);
extern char* azuretls_session_apply_ja3(GoUintptr sessionID, char* ja3, char* navigator, char* tlsSpecifications);
extern char* azuretls_session_apply_http2(GoUintptr sessionID, char* fingerprint);
extern char* azuretls_session_apply_http3(GoUintptr sessionID, char* fingerprint);
extern char* azuretls_session_set_proxy(GoUintptr sessionID, char* proxy);
extern void azuretls_session_clear_proxy(GoUintptr sessionID);
extern char* azuretls_session_add_pins(GoUintptr sessionID, char* urlStr, char* pinsJSON);
extern char* azuretls_session_clear_pins(GoUintptr sessionID, char* urlStr);
extern char* azuretls_session_get_ip(GoUintptr sessionID);
extern char* azuretls_session_get_cookies(GoUintptr sessionID, char* urlStr);
extern char* azuretls_session_new_websocket(GoUintptr sessionId, char* config, GoUintptr* outWsSessionId);
extern void azuretls_websocket_close(GoUintptr sessionID);
extern char* azuretls_websocket_read_message(GoUintptr sessionID, GoInt* outMessageType, char** output, GoInt* length);
extern char* azuretls_websocket_write_message(GoUintptr sessionID, GoInt messageType, char* message, GoInt length);
extern void azuretls_free_string(char* str);
extern void azuretls_free_response(CFfiResponse* resp);
extern char* azuretls_version();
extern void azuretls_init();
extern void azuretls_cleanup();

#ifdef __cplusplus
}
#endif
